name: Main
version: '${project.version}'
main: me.justplugins.SuperEssentials.Main
authors: [ Nathan, D1TZ ]
description: "Everything basic needed for your Minecraft server"
website: justplugins.xyz
api-version: 1.13
